"""
The program is painting Python's icon
"""
import turtle

#The first snake painting
turtle.penup()
turtle.setx(40)
turtle.sety(40)
turtle.pendown()
turtle.begin_fill()
turtle.pensize(2)
turtle.pencolor("#306998")
turtle.fillcolor("#4B8BBE")
turtle.forward(35)
turtle.circle(30,90) 
turtle.forward(50)
turtle.left(40)
turtle.circle(60,100) 
turtle.left(40)
turtle.forward(35)
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(12)
turtle.right(90)
turtle.forward(85)
turtle.left(40)
turtle.circle(60,100)
turtle.left(40)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.right(10)
turtle.circle(-35,90)
turtle.left(20) 
turtle.forward(1)
turtle.end_fill()
turtle.penup()
turtle.end_fill()
turtle.penup()
turtle.pendown()

#The second snake painting
turtle.penup()
turtle.right(190)
turtle.setx(80)
turtle.sety(30)
turtle.pendown()
turtle.begin_fill()
turtle.pensize(2)
turtle.pencolor("#FFD43E")
turtle.fillcolor("#FFE873")
turtle.forward(35)
turtle.circle(30,90) 
turtle.forward(50)
turtle.left(40)
turtle.circle(60,100) 
turtle.left(40)
turtle.forward(35)
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(12)
turtle.right(90)
turtle.forward(85)
turtle.left(40)
turtle.circle(60,100)
turtle.left(40)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.right(10)
turtle.circle(-35,90)
turtle.left(20) 
turtle.end_fill()
turtle.penup()

#Drawing the first circle
turtle.penup()
turtle.setx(30)
turtle.sety(120)
turtle.pendown()
turtle.begin_fill()
turtle.pensize(1)
turtle.pencolor("#646464")
turtle.fillcolor("#FFFFFF")
turtle.circle(7,360) 
turtle.end_fill()
turtle.penup()

#Drawing the second circle
turtle.setx(85)
turtle.sety(-40)
turtle.pendown() 
turtle.begin_fill()
turtle.pensize(1)
turtle.pencolor("#646464")
turtle.fillcolor("#FFFFFF")
turtle.circle(7,360) 
turtle.end_fill()
turtle.penup()

turtle.done()
